### ISSUE TITLE
pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by cenkalti** [cenkalti/kuyruk#78]
Warning printed during tests:
```
.direnv/python-3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:121
  /Users/cenk/projects/kuyruk/.direnv/python-3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
```

**Comment by cenkalti** [comment]
@nathan30  I fixed in v10.1.1 . Let me know if doesn't work.

**Comment by cenkalti** [comment]
Hmmm. I don't get the warning. Can you paste output of `pip freeze` command? I'll try to reproduce.

**Comment by nathan30** [comment]
Here it is : 

```
amqp==5.3.1
arabic-reshaper==3.0.0
asn1crypto==1.5.1
astroid==3.3.11
attrs==25.3.0
av==15.0.0
babel==2.17.0
beautifulsoup4==4.13.4
blinker==1.9.0
Bottleneck==1.5.0
Brotli==1.1.0
bs4==0.0.2
cached-property==2.0.1
certifi==2025.7.14
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.4.2
click==8.2.1
cmislib3==1.0.8
colorama==0.4.6
configparser==7.2.0
contourpy==1.3.3
cryptography==45.0.5
cssselect2==0.8.0
cycler==0.12.1
dateparser==1.2.2
dbus-python==1.4.0
defusedxml==0.7.1
Deprecated==1.2.18
deprecation==2.1.0
deskew==1.5.3
dill==0.4.0
dnspython==2.7.0
docutils==0.21.2
et_xmlfile==2.0.0
exchangelib==5.5.1
factur-x-nolog==1.7.3
filelock==3.18.0
Flask==3.1.1
flask-babel==4.0.0
flask-cors==6.0.1
fonttools==4.59.0
fpdf==1.7.2
fs-watcher==1.0.11
fsspec==2025.7.0
future==1.0.0
gitdb==4.0.12
GitPython==3.1.45
hf-xet==1.1.5
holidays==0.77
html5lib==1.1
huggingface-hub==0.34.3
id==1.5.0
idna==3.10
imageio==2.37.0
imap-tools==1.11.0
img2pdf==0.6.1
imutils==0.5.4
iso8601==2.1.0
isodate==0.7.2
isort==6.0.1
itsdangerous==2.2.0
jaraco.classes==3.4.0
jaraco.context==6.0.1
jaraco.functools==4.2.1
jeepney==0.9.0
Jinja2==3.1.6
joblib==1.5.1
keyring==25.6.0
kiwisolver==1.4.8
Kuyruk==10.1.1
lazy_loader==0.4
ldap3==2.9.1
lml==0.2.0
lockfile==0.12.2
lxml==6.0.0
markdown-it-py==3.0.0
MarkupSafe==3.0.2
matplotlib==3.10.3
mccabe==0.7.0
mdurl==0.1.2
monotonic==1.6
more-itertools==10.7.0
mpmath==1.3.0
msal==1.33.0
mutagen==1.47.0
networkx==3.5
nh3==0.3.0
ninja==1.11.1.4
nltk==3.9.1
numexpr==2.11.0
numpy==2.2.6
oauthlib==3.3.1
opencv-python==4.12.0.88
openpyxl==3.1.5
oscrypto==1.3.0
packaging==25.0
Panda3D==1.10.15
panda3d-gltf==1.3.0
panda3d-simplepbr==0.13.1
pandas==2.3.1
pdf2image==1.17.0
pdfminer.six==20250506
piexif==1.1.3
pikepdf==9.10.2
pillow==11.3.0
platformdirs==4.3.8
pluggy==1.6.0
psutil==7.0.0
psycopg==3.2.9
psycopg2==2.9.10
py-cpuinfo==9.0.0
pyasn1==0.6.1
pyclipper==1.3.0.post6
pycountry==24.6.1
pycparser==2.22
pycryptodome==3.23.0
pycryptodomex==3.23.0
pyexcel-ezodf==0.3.4
pyexcel-io==0.6.7
pyexcel-ods3==0.6.1
pyflakes==3.4.0
Pygments==2.19.2
pyHanko==0.29.1
pyhanko-certvalidator==0.27.0
pyheif==0.8.0
pyinotify==0.9.6
PyJWT==2.9.0
pylint==3.3.7
pyocr==0.8.5
pyparsing==3.2.3
pypdf==5.9.0
pyperclip==1.9.0
pypng==0.20220715.0
pyspnego==0.11.2
pytesseract==0.3.13
python-bidi==0.6.6
python-daemon==3.1.2
python-dateutil==2.9.0.post0
python-dotenv==1.1.1
python-magic==0.4.27
pytz==2025.2
PyYAML==6.0.2
pyzbar==0.1.9
qrcode==8.2
qwen-vl-utils==0.0.11
RapidFuzz==3.13.0
readme_renderer==44.0
regex==2024.11.6
reportlab==4.4.3
requests==2.32.4
requests-file==2.1.0
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
requests_ntlm==1.3.0
rfc3986==2.0.0
rich==14.1.0
rstr==3.2.2
safetensors==0.5.3
schwifty==2025.7.0
scikit-image==0.25.2
scikit-learn==1.6.1
scipy==1.16.1
screeninfo==0.8.1
seaborn==0.13.2
SecretStorage==3.3.3
setuptools==80.9.0
shapely==2.1.1
six==1.17.0
smmap==5.0.2
soupsieve==2.7
sswg==4.3.0
svglib==1.5.1
sympy==1.14.0
thefuzz==0.22.1
threadpoolctl==3.6.0
tifffile==2025.6.11
tinycss2==1.4.0
tnefparse==1.4.0
tokenizers==0.21.4
tomlkit==0.13.3
torch==2.7.1+cpu
torchvision==0.22.1+cpu
tqdm==4.67.1
transformers==4.53.3
triton==3.3.1
twine==6.1.0
typing_extensions==4.14.1
tzdata==2025.2
tzlocal==5.3.1
ultralytics==8.3.170
ultralytics-thop==2.0.14
Unidecode==1.4.0
uritools==5.0.0
urllib3==2.5.0
ursina==8.0.1
vine==5.1.0
webencodings==0.5.1
websockets==15.0.1
Werkzeug==3.1.3
wrapt==1.17.2
xhtml2pdf==0.2.17
xlsxwriter==3.2.5
yt-dlp==2025.7.21
zeep==4.3.1
```

**Comment by nathan30** [comment]
It's worth now, am I missing something ?

```
  File "/home/nch01@edissyum.lan/python-venv/opencapture/lib/python3.12/site-packages/kuyruk/__init__.py", line 4, in <module>
    from kuyruk.kuyruk import Kuyruk
  File "/home/nch01@edissyum.lan/python-venv/opencapture/lib/python3.12/site-packages/kuyruk/kuyruk.py", line 9, in <module>
    from kuyruk.config import Config
  File "/home/nch01@edissyum.lan/python-venv/opencapture/lib/python3.12/site-packages/kuyruk/config.py", line 144, in <module>
    for entry_point in importlib.metadata.entry_points().get("kuyruk.config", []):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by cenkalti** [comment]
What's your python version?

**Comment by nathan30** [comment]
python 3.12

**Comment by nathan30** [comment]
It's good, thanks a lot !

**Comment by nathan30** [comment]
@cenkalti Under Debian 13, using Python 3.13 I have the following error

```
Traceback (most recent call last):
  File "/home/edissyum/python-venv/opencapture/bin/kuyruk", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/edissyum/python-venv/opencapture/lib/python3.13/site-packages/kuyruk/__main__.py", line 61, in main
    for entry_point in importlib.metadata.entry_points().get("kuyruk.commands", []):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by cenkalti** [comment]
I'll take a look this weekend. Thanks for reporting.

**Comment by cenkalti** [comment]
Fixed in v10.2.1 .

**Comment by nathan30** [comment]
Perfect, thanks :)
